### ISSUE TITLE
Should the DID Document data model be moved to the DID Resolution spec?

### ISSUE THREAD

**Issue by mwherman2000** [w3c/did-resolution#15]
[Duplicate of DID spec comment: https://github.com/w3c-ccg/did-spec/issues/151#issuecomment-461417659]

Where should DID Documents be defined/spec'ed out? ...given that they are exclusively an output of the DID Resolution process?

Digging deeper...

1. Is there an analogy/are there parallels between:
    - the DID and DID Document "information architecture", and
    - the IP Address/TCP-IP/DNS information architecture?

2. Is the IP Address/TCP/IP information architecture analogous to DIDs?
   ...similar to the way DID Documents are to DNS entries?

3. If it doesn't make sense to spec DNS entries in the IP/TCP-IP specs, why are we trying to spec DID Documents in the DID spec (instead of the DID Resolution spec)?

Reference: Here's a DNS primer that some people might find helpful (DNS is much more than a `domain name` => `IP address` resolver):
https://hyperonomy.com/2019/01/02/dns-domain-name-service-a-detailed-high-level-overview/

Here's an updated version of the DID 6-Layer Model to illustrate the above point...

![image](https://user-images.githubusercontent.com/6101736/52415166-83c0d780-2aa3-11e9-90d5-b9bd3bb6b1f6.png)

**Comment by mwherman2000** [comment]
Cross-reference: https://github.com/w3c-ccg/community/issues/20 - DID Resolution spec "charter"

**Comment by mwherman2000** [comment]
The DID Document data model being defined by the DID Resolution spec is supported by the following statement in the Introduction https://w3c-ccg.github.io/did-resolution/#introduction.  It states...

> This specification defines common requirements, input parameters and output data, architectural options, and various considerations for the DID Resolution process.

**Comment by mwherman2000** [comment]
Being discussed/answered here: https://github.com/w3c-ccg/did-resolution/issues/18#issuecomment-461663993

**Comment by peacekeeper** [comment]
@mwherman2000 I think the consensus was that the DID (Document) data model would NOT be moved to the DID Resolution spec. Is there any reason why you re-opened this issue?

**Comment by mwherman2000** [comment]
@peacekeeper ...only because I had clicked on the `Close and comment` button by mistake :-)

**Comment by peacekeeper** [comment]
Okay I see. How about then we close this issue now and discuss the diagram on the other open issue #18 ?

**Comment by peacekeeper** [comment]
@mwherman2000 considering this thread, and this comment https://github.com/w3c-ccg/did-resolution/issues/18#issuecomment-461663993, and this thread https://github.com/w3c-ccg/did-spec/issues/167, I believe the consensus is that the DID Document data model will NOT be moved to the DID Resolution spec. So we can close this issue, do you agree?

**Comment by peacekeeper** [comment]
I think this issue can be closed, since it's clear that the DID document data model will not be moved to the DID Resolution spec.

In fact, there is an ongoing discussion now whether DID Core should be updated to reference the [Controller Document Specification](https://w3c.github.io/controller-document/):

https://github.com/w3c/did-core/issues/854

**Comment by peacekeeper** [comment]
Closing, as discussed in today's DID WG meeting.
