### ISSUE TITLE
How will I be able to enumerate/search/retrieve-in-batches all of the DID Documents represented on a given Ledger?

### ISSUE THREAD

**Issue by mwherman2000** [w3c/did-resolution#20]
Using the DID Resolution protocol, wow will I be able to enumerate/search/retrieve-in-batches all of the DID Documents represented on a given Ledger?

**Comment by dmitrizagidulin** [comment]
A very interesting question! Each DID method / implementation will have to decide on how to answer that. 
(I'm curious about this one, too.)

**Comment by peacekeeper** [comment]
My answer would be:

1. It's method-specific, some methods will support it, some won't.
2. Details of how to do it are out of scope for this spec, but we could perhaps have a paragraph somewhere with a few high-level considerations?

**Comment by peacekeeper** [comment]
Coming back to this issue after a while, I still believe that specifying this feature is out-of-scope, but could be mentioned somewhere in a paragraph.

**Comment by peacekeeper** [comment]
@mwherman2000 Up to you I think, since you opened this issue originally. I think it's clear that we won't define an algorithm or protocol or API for this in this specification. But if you like, you could create a pull request to add a paragraph or subsection somewhere to mention that such a functionality is possible and may be defined in a separate specification in the future.

**Comment by mwherman2000** [comment]
Web 7.0 is on a slightly different trajectory: https://github.com/Web7Foundation/Specifications/blob/main/methods/did-ns-1-0-1.md#variations . I will close this issue.

> Three (3) variations of the did:ns DID method are currently supported.
> 
> - DID Name System over DNS (DIDNS/DNS) (reference implementation)
> - DID Name System over Microsoft Active Directory/Azure Directory Services (DIDNS/AD)
> - DID Name System over X.500/LDAP (DIDNS/LDAP)
> 
> This specification describes the design of the DIDNS/DNS reference implementation.
