### ISSUE TITLE
Support "proxy" service type?

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-resolution#35]
Keeping track of a proposal here https://github.com/w3c-ccg/did-spec/issues/90#issuecomment-439936749 that a DID Document could contain a "proxy" service type which would provide a mapping that needs to be followed in order to resolve to a final service URL.

**Comment by pchampin** [comment]
This was discussed during the [did meeting on 17 October 2024](https://www.w3.org/2024/10/17-did-minutes.html#69b9).

<details><summary><i>View the transcript</i></summary>

<h4><a href="https://github.com/w3c/did-resolution/issues/35" rel="noopener noreferrer">w3c/<wbr>did-resolution#35</a></h4>
<p><cite>markus_sabadello:</cite> I opened this a five years ago, there was an issue in the DID spec about potential privacy concerns associated with data in the DID Document itself, like service endpoints, idea was that if you include service endpoints, endpoints could be sensitive or correlatable, idea was to introduce a proxy service type where you could look up what is normally in the DID Document but use a remote service for looking up parts of the DID Document to not<br>
<span>… include correlatable information in the DID DOcument itself. Wonder what we should do with this?</span></p>
<p><cite>markus_sabadello:</cite> We can mark this an enhancement for now... in five years, no one has worked on this, or had a real life need for this.</p>
<p><cite>manu:</cite> Dave Longley wrote something about this, I don't think we have anyone working on that right now.<br>
<span>… We have a number of DIDs floating on the Web, and people use those DIDs to discover how to interact with the DID controller.</span><br>
<span>… But this is not how things operate now; DID controllers identify with their DID, then use some web service to start an interaction.</span></p>
<p><cite>markus_sabadello:</cite> I agree, if anyone ever specifies/implements this, it's a service type so just like defining a different service type like DIDComm or OpenID, so probably be in a separate spec anyway and registered as an extension. Doesn't feel like something that needs to be in DID Resolution itself.</p>
<p><cite>Wip:</cite> How do we process this issue? "lacks interest"?</p>
<p><cite>markus_sabadello:</cite> I opened this, could add comment -- this could be useful as an extension, but doesn't need to be in DID Resolution.</p>
<p><cite>Wip:</cite> That's all we have time for today, any particular issues that could deal with some attention next week?</p>
<p><cite>markus_sabadello:</cite> Not sure right now, I'll look.</p>

<hr /></details>

**Comment by peacekeeper** [comment]
Closing after today's DID WG meeting.
