### ISSUE TITLE
Add JSON-LD context to example resolution result

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c/did-resolution#4]
Add JSON-LD `@context` to the existing example.

What should the context be? @msporny - where's the best place to host it? (it being the ontology description etc)

**Comment by msporny** [comment]
> What should the context be? @msporny - where's the best place to host it? (it being the ontology description etc)

I suggest setting up a https://w3id.org/ redirect. You can then host both the JSON-LD Context file and the ontology via Github. Example here:

https://github.com/perma-id/w3id.org/blob/master/security/.htaccess

**Comment by peacekeeper** [comment]
Marking this as "pending-close", since all example resolution results in the spec have JSON-LD contexts by now, a w3id.org redirect exists, and the question what the context should be is now also being discussed in https://github.com/w3c/did-resolution/issues/78.

**Comment by peacekeeper** [comment]
Closing, as discussed in today's DID WG meeting.
