### ISSUE TITLE
Parameter and metadata naming conventions

### ISSUE THREAD

**Issue by clehner** [w3c/did-resolution#62]
`did-resolution` uses kebab-case (e.g. `content-type`) for metadata property names and DID parameter names, but `did-core` uses camelCase (e.g. `contentType`). Should `did-resolution` be changed to match `did-core` in this?

Edit: `did-spec-registries` also updated to use camelCase: https://github.com/w3c/did-spec-registries/pull/256

**Comment by peacekeeper** [comment]
I believe that this issue can be closed, since by now DID Resolution uses camelCase for property names and DID parameter names, just like DID Core.

**Comment by peacekeeper** [comment]
Closing, as discussed in today's DID WG meeting.
