### ISSUE TITLE
Create DID resolution test suite

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-resolution#64]
The [DID test suite](https://github.com/w3c/did-test-suite) has sections on DID resolution and DID URL deferencing, however those don't actually test live resolvers (since that was out-of-scope for the DID Core specification). The DID Resolution specification does define a concrete [HTTP(S) binding](https://w3c-ccg.github.io/did-resolution/#bindings-https) as well as a concrete representation of a [DID resolution result](https://w3c-ccg.github.io/did-resolution/#did-resolution-result). Therefore, a DID Resolution test suite should be created to test those additional pieces of functionality.

The [VC HTTP API test suite](https://github.com/w3c-ccg/vc-http-api/) depends on DID Resolution to some degree, but there is interest in minimizing that component and move it to this work item here.

**Comment by OR13** [comment]
I support this proposal.

In particular I think it's important to standardize resolution and dereferencing over https.

Especially as they relate to Verifiable Credentials.

At one point a while ago, i wrote a script that consumed the universal resolver config and then resolved all the did documents and "consumed / produced" them as JSON-LD to detect errors.

I think we could probably do something similar here, and maybe even use the JSON Schema and SHACL associated with did core.


Another thing I have noticed is returning the `didDocument, metadata` in the response body vs `didDocument` as the response body. I assume we have the same issue for dereference (with or without meta) as the response body or in it.

The did core spec is flexbile here, but we can make recommendations that reduce complexity.

**Comment by peacekeeper** [comment]
There has been a DID resolution test suite in the W3C CCG for a while now: https://github.com/w3c-ccg/did-resolution-test-suite.

In addition, there are also test suites for specific DID methods, e.g.: https://github.com/w3c-ccg/did-key-test-suite

So I think we can close this issue.

**Comment by peacekeeper** [comment]
Closing, as discussed in today's DID WG meeting.
