### ISSUE TITLE
Initial feedback on major sections: DID Resolution and DID URL Dereferencing Algorithms

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-resolution#80]
During the [25th July 2024 DID WG call](https://lists.w3.org/Archives/Public/public-did-wg/2024Jul/0033.html), I mentioned "DID Resolution and DID URL Dereferencing Algorithms" as one of four major topics for this spec. See here:

- https://w3c.github.io/did-resolution/#resolving
- https://w3c.github.io/did-resolution/#dereferencing

The idea of these sections is to define algorithms for the DID Resolution and DID URL Dereferencing functions, e.g. what steps a resolver executes, how it processes certain DID parameters, what metadata to return in certain situations, how much of the process is method-specific and how much is method-independent, and how extensibility of the process is possible.

Any feedback is welcome, and I'd be most interested in high-level opinions on whether this is indeed an important topic that should be covered by the spec, and in thoughts on the general direction of this topic.

**Comment by peacekeeper** [comment]
During the 29 Aug 2024 DID WG call, it has been mentioned that perhaps the terms "primary resource" and "secondary resource" could be confusing to readers, and that we should better emphasize that in many "default" cases, the result of dereferencing is simply a DID document, and that processing of the fragment takes place as defined by the media type.

**Comment by pchampin** [comment]
This was discussed during the did meeting on 2024-08-29:
https://www.w3.org/2024/08/29-did-minutes.html#t06

**Comment by peacekeeper** [comment]
Marking as pending-close, since this has been discussed on a high level.

For now, two concrete new issues have been identified related to this topic:
- https://github.com/w3c/did-resolution/issues/94
- https://github.com/w3c/did-extensions/issues/582
