### ISSUE TITLE
Initial feedback on major sections: DID Resolution Architectures

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-resolution#81]
During the [25th July 2024 DID WG call](https://lists.w3.org/Archives/Public/public-did-wg/2024Jul/0033.html), I mentioned "DID Resolution Architectures" as one of four major topics for this spec. See here:

- https://w3c.github.io/did-resolution/#architectures

The idea of this section is to explain topics related to how resolvers are deployed and used, e.g. that a "resolver" can be a local or remote component, that DID methods can involve local processing or remote processing communication, that resolvers could potentially proxy or redirect to other resolvers, and that a DID document could be resolved by a remote service, but various DID parameters and the fragment could also be dereferenced locally by a client.

Any feedback is welcome, and I'd be most interested in high-level opinions on whether this is indeed an important topic that should be covered by the spec, and in thoughts on the general direction of this topic.

**Comment by pchampin** [comment]
This was discussed during the did meeting on 2024-08-29:
https://www.w3.org/2024/08/29-did-minutes.html#t06

**Comment by mccown** [comment]
Resolvers, inherently, provide a natural point where the resolver provider can log requests and use them for tracking or profiling.  One sub-section worth adding might be a short discussion on ways that resolutions could be performed while also minimizing the extent by which requestors could be profiled.

**Comment by peacekeeper** [comment]
Related issue: https://github.com/w3c/did-resolution/issues/28

**Comment by peacekeeper** [comment]
@mccown I think that is good feedback regarding logging, tracking, profiling of the clients. Could you maybe create a separate issue for that?

**Comment by peacekeeper** [comment]
Marking as pending-close, since this has been discussed on a high level.

For now, one concrete issue has been identified related to this topic:
- https://github.com/w3c/did-resolution/issues/95
