### ISSUE TITLE
Initial feedback on major sections: Serializations of DID Resolution Result and DID URL Dereferencing Result

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-resolution#82]
During the [25th July 2024 DID WG call](https://lists.w3.org/Archives/Public/public-did-wg/2024Jul/0033.html), I mentioned "Serializations of DID Resolution Result and DID URL Dereferencing Result" as one of four major topics for this spec. See here:

- https://w3c.github.io/did-resolution/#did-resolution-result
- https://w3c.github.io/did-resolution/#did-url-dereferencing-result

The idea of this section is to define the outputs of the DID Resolution and DID URL Dereferencing functions not just in abstract way, but also a concrete JSON-LD serialization format, that includes e.g. the DID document plus DID document metadata plus DID resolution metadata.

Any feedback is welcome, and I'd be most interested in high-level opinions on whether this is indeed an important topic that should be covered by the spec, and in thoughts on the general direction of this topic.

**Comment by jandrieu** [comment]
+1 to a concrete serialization.

**Comment by pchampin** [comment]
This was discussed during the WG meeting on 2024-08-22:
https://www.w3.org/2024/08/22-did-minutes.html#t13

**Comment by pchampin** [comment]
This was discussed during the did meeting on 2024-08-29:
https://www.w3.org/2024/08/29-did-minutes.html#t06

**Comment by peacekeeper** [comment]
Marking as pending-close, since this has been discussed on a high level. For now, no concrete issue has been identified related to this topic.
