### ISSUE TITLE
DID = Base IRI?

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-resolution#9]
DID Resolution returns a DID Document, which is JSON-LD. While parsing JSON-LD, we could specify that the Base IRI is set to the original DID that is being resolved. This would enable easy use of relative IRIs in the DID Document.

**Comment by mwherman2000** [comment]
IRI? ...it's not defined in the current spec.

**Comment by peacekeeper** [comment]
Internationalized Resource Identifier (= internationalized version of URI), see https://tools.ietf.org/html/rfc3987

**Comment by peacekeeper** [comment]
> While parsing JSON-LD, we could specify that the Base IRI is set to the original DID that is being resolved. 

A slightly different and perhaps better idea is that the Base IRI is set to the value of the `id` property of the DID Document. See comment here https://github.com/w3c-ccg/did-spec/issues/97#issuecomment-511684511.

**Comment by talltree** [comment]
@peacekeeper I like that last idea. However I'm wondering if we can't skip IRI and just use URI, i.e., RFC 3986, since the syntax of DIDs is so restricted anyway (on purpose—to avoid some of the very complex string matching rules involved with IRIs vs. URIs). Thoughts?

**Comment by peacekeeper** [comment]
@talltree Hmm "Base IRI" is the term used by the JSON-LD spec, so I thought we'd stick with that..?

**Comment by talltree** [comment]
@peacekeeper While I understand that, I believe the DID spec should specify DID syntax is restricted to RFC 3986 URI syntax (not RFC 3987 IRI syntax) because:

- DIDs are not intended to be human-friendly identifiers so we don't need the features of IRIs
- URIs are easier than IRIs to do string comparisons on to determine equivalence
- We have already tightly restricted the syntax of DIDs to make comparison (and human transcription) easier and avoid homonym attacks.

Make sense?

**Comment by peacekeeper** [comment]
I think that's fine.. Since URIs are also IRIs that would still be compatible with JSON-LD.

**Comment by peacekeeper** [comment]
This is being discussed in https://github.com/w3c/did-core/pull/408.

**Comment by peacekeeper** [comment]
Also see discussion in https://github.com/w3c/did-core/issues/432.

**Comment by peacekeeper** [comment]
I believe that this issue can be closed, since the question of the Base IRI has been addressed in DID Core, e.g. in the section about [Relative DID URLs](https://www.w3.org/TR/did-core/#relative-did-urls).

**Comment by peacekeeper** [comment]
Closing, as discussed in today's DID WG meeting.
